### ISSUE TITLE
dictable error

### ISSUE THREAD

**Issue by rzftm** [gityoav/pyg-base#2]
package version:
python 3.8.16
pandas 1.5.3
numpy 1.23.5
pyg-base 0.0.52

run this:
s = dictable(a=[1,2,3,4])
s = s(b=lambda a: a * 2)

error:
Traceback (most recent call last):
  File "h:/_CODE/firstpkg/src/ecm/atom/template/package/pyg_example.py", line 4, in <module>        
    s = s(b=lambda a: a * 2)
  File "\\NYFILE03\HomeDrives\rzhao\src\pyg-base\src\pyg_base\_dict.py", line 88, in __call__       
    res[key] = self._postprocess(key, res.apply(value, **{self._key : key}))
  File "\\NYFILE03\HomeDrives\rzhao\src\pyg-base\src\pyg_base\_dictable.py", line 598, in apply     
    return [f(**(default_params|row)) for row in self]
  File "\\NYFILE03\HomeDrives\rzhao\src\pyg-base\src\pyg_base\_dictable.py", line 598, in <listcomp>
    return [f(**(default_params|row)) for row in self]
TypeError: unsupported operand type(s) for |: 'dict' and 'Dict'

Maybe a python version issue?

**Comment by gityoav** [comment]
yes, this is using a 3.9 python functionality. changed code to work with 3.6
